export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const AUTH_START = 'AUTH_START';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REDUCE_CART_ITEM = 'REDUCE_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const SET_SHIPPING_INFO = 'SET_SHIPPING_INFO';

export const SET_USER_ORDER_HISTORY = 'SET_USER_ORDER_HISTORY';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';
export const SET_ORDER_INIT = 'SET_ORDER_INIT';
